name: Label Deployments

on:
  deployment_status:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: deploy-label-${{ github.event.deployment.environment }}

    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ github.event.action }}
          echo ${{ github.event.deployment_status.state }}
          echo ${{ github.event.deployment.environment }}
          echo ${{ github.event.deployment.ref }}
      
      - name: Get issue number
        id: find_issue
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query findIssue {
              search(type: ISSUE, query: "repo:${{ github.event.repository.full_name }} in:title ${{ github.event.deployment.environment }}", first: 1) {
                nodes {
                  ... on Issue {
                    number
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: environment_issue
        run: echo ::set-output name=number::'${{ fromJson(steps.find_issue.outputs.data).search.nodes[0].number }}'
      
      - run: echo Todo, remove existing react labels
      
      - name: Add deploying label to issue
        if: contains(fromJson('["waiting", "in_progress"]'), github.event.deployment_status.state)
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: Deploying React...
          number: ${{ steps.environment_issue.outputs.number }}

      - name: Remove deploying label from issue
        if: contains(fromJson('["success", "failed"]'), github.event.deployment_status.state)
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Deploying React...
          number: ${{ steps.environment_issue.outputs.number }}

      - name: Add deployed branch label to issue
        if: github.event.deployment_status.state == 'success'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: React ${{ github.event.deployment.ref }}
          number: ${{ steps.environment_issue.outputs.number }}
