name: Build and Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Deploy to
jobs:
  check:
    runs-on: ubuntu-latest
    name: Lint and test
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        run: echo Linting ${{ github.ref }}
        
      - name: Test
        run: echo Testing ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: check

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo Building ${{ github.ref }}!

  deploy-manual:
    uses: aarontwf/actions-playground/.github/workflows/deploy.yaml@main
    needs: build
    if: github.event_name == 'workflow_dispatch'
    with:
      environment: ${{ github.event.inputs.environment }}

  
  deploy-staging-01:
    uses: aarontwf/actions-playground/.github/workflows/deploy.yaml@main
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      environment: Staging 01

  deploy-staging-02:
    uses: aarontwf/actions-playground/.github/workflows/deploy.yaml@main
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      environment: Staging 02

  deploy-production:
    uses: aarontwf/actions-playground/.github/workflows/deploy.yaml@main
    needs: [deploy-staging-01, deploy-staging-02]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      environment: Production
