name: JIRA test

on:
  workflow_dispatch:
    inputs:
      release_name:
        type: text
        required: true
        description: Release Name
      is_released:
        type: boolean
        required: true
        description: Mark as released?

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: cartoncloud/create-jira-release-action@main
        with:
          username: ${{ secrets.JIRA_USERNAME }}
          password: ${{ secrets.JIRA_PASSWORD }}
          serverAddress: support.cartoncloud.com
          projectId: 10204
          releaseName: ${{ github.event.inputs.release_name }}
          isReleased: ${{ github.event.inputs.is_released == 'true' }}
          description: Test JIRA GitHub Action
