name: Branch Labels

on:
  [create, delete]

jobs:
  create-label:
    name: Create branch label
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'create' && github.event.ref_type == 'branch' }}

    steps:
      - uses: aarontwf/create-delete-label-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: React ${{ github.event.ref }}
          description: ${{ github.event.ref }} branch
          color: '#d73a4a'
          action: create

  delete-label:
    name: Delete branch label
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'delete' && github.event.ref_type == 'branch' }}

    steps:

      - uses: aarontwf/create-delete-label-action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: React ${{ github.event.ref }}
          action: delete
