name: Deploy to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Deploy to
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo Building ${{ github.ref }}!

  deploy:
    name: Deploy
    uses: aarontwf/actions-playground/.github/workflows/deploy.yaml@main
    needs: build
    with:
      environments: ${{ format('["{0}"]', github.event.inputs.environment) }}
