name: Deploy to Environment
concurrency: deploy-${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Deploy to
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo Building ${{ github.ref }}!

  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ github.event.inputs.environment }}
    
    steps:
      - run: echo Deploying ${{ github.ref }} to ${{ github.event.inputs.environment }}!
