name: CI
concurrency: release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo Hello, World ${{ github.ref }}!

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        environment: [Staging 01, Staging 02]
    environment: ${{ matrix.environment }}
    name: Deploy to ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: echo Hello ${{ matrix.environment }}!

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    name: Deploy to Production

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: echo Hello Production!
