name: Release

on:
  release:

jobs:
  log:
    name: Log
    runs-on: ubuntu-latest

    steps:
      - name: Log details
        run: |
          echo "Action: ${{ github.event.action }}"
          echo "Name: ${{ github.event.release.name }}"
          echo "Tag Name: ${{ github.event.release.tag_name }}"
          echo "Pre-release: ${{ github.event.release.prerelease }}"
